language: C++
sudo: false
dist: trusty

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.8
          packages:
            - [ 'clang-3.8', 'ninja-build' ]
      env:
        - CMAKE_BUILD_TYPE=DEBUG
        - MATRIX_EVAL="CC=clang-3.8 && CXX=clang++-3.8"

before_install:
  - eval "${MATRIX_EVAL}"

script:
  - python ./utils/make_build.py -D PSTORE_EXAMPLES=Yes
  - ninja -C build_linux all pstore-system-tests
