language: cpp
sudo: false

matrix:
  include:
    - os: linux
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.8
          packages:
            - [ 'clang-3.8', 'ninja-build' ]
      env:
        - CMAKE_BUILD_TYPE=DEBUG
        - MATRIX_EVAL="CC=clang-3.8 && CXX=clang++-3.8"

#    - os: linux
#      dist: trusty
#      addons:
#        apt:
#          sources:
#            - ubuntu-toolchain-r-test
#          packages:
#            - [ 'g++-5', 'ninja-build' ]
#      env:
#        - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"

    - os: osx
      osx_image: xcode9.3


before_install:
  - eval "${MATRIX_EVAL}"

script:
  - ./utils/make_build.py -o build -D PSTORE_EXAMPLES=Yes
  - cmake --build build
  - cmake --build build --target pstore-system-tests
