name: CI Build/Test
# Triggers the workflow on push or pull request events
on: [push, pull_request]
jobs:
    build:
        strategy:
            matrix:
                include:
                    - name: macOS-latest/Xcode/Debug
                      build_type: Debug
                      generator: Xcode
                      options: '-DPSTORE_ALWAYS_SPANNING=Yes'
                      os: macos-latest

                    - name: macOS-latest/Xcode/Release
                      build_type: Release
                      generator: Xcode
                      os: macos-latest


                    - name: Ubuntu-latest/gcc-7.5/Debug
                      apt_name: g++-7
                      build_type: Debug
                      cxx_compiler: -DCMAKE_CXX_COMPILER=g++-7 -DCMAKE_C_COMPILER=gcc-7
                      generator: Unix Makefiles
                      options: '-DPSTORE_ALWAYS_SPANNING=Yes'
                      os: ubuntu-latest

                    - name: Ubuntu-latest/gcc-7.5/Release
                      apt_name: g++-7
                      build_type: Release
                      cxx_compiler: -DCMAKE_CXX_COMPILER=g++-7 -DCMAKE_C_COMPILER=gcc-7
                      generator: Unix Makefiles
                      os: ubuntu-latest


                    - name: Ubuntu-latest/gcc-10/Debug
                      build_type: Debug
                      cxx_compiler: -DCMAKE_CXX_COMPILER=g++-10 -DCMAKE_C_COMPILER=gcc-10
                      generator: Unix Makefiles
                      options: '-DPSTORE_ALWAYS_SPANNING=Yes'
                      os: ubuntu-latest

                    - name: Ubuntu-latest/gcc-10/Release
                      build_type: Release
                      cxx_compiler: -DCMAKE_CXX_COMPILER=g++-10 -DCMAKE_C_COMPILER=gcc-10
                      generator: Unix Makefiles
                      os: ubuntu-latest


                    - name: Ubuntu-latest/clang-8/Debug
                      apt_name: clang-8
                      build_type: Debug
                      cxx_compiler: -DCMAKE_CXX_COMPILER=clang++-8 -DCMAKE_C_COMPILER=clang-8
                      generator: Unix Makefiles
                      options: '-DPSTORE_ALWAYS_SPANNING=Yes'
                      os: ubuntu-latest

                    - name: Ubuntu-latest/clang-8/Release
                      apt_name: clang-8
                      build_type: Release
                      cxx_compiler: -DCMAKE_CXX_COMPILER=clang++-8 -DCMAKE_C_COMPILER=clang-8
                      generator: Unix Makefiles
                      os: ubuntu-latest


                    - name: Ubuntu-latest/clang-9/Debug
                      build_type: Debug
                      cxx_compiler: -DCMAKE_CXX_COMPILER=clang++-9 -DCMAKE_C_COMPILER=clang-9
                      generator: Unix Makefiles
                      options: '-DPSTORE_ALWAYS_SPANNING=Yes'
                      os: ubuntu-latest

                    - name: Ubuntu-latest/clang-9/Release
                      build_type: Release
                      cxx_compiler: -DCMAKE_CXX_COMPILER=clang++-9 -DCMAKE_C_COMPILER=clang-9
                      generator: Unix Makefiles
                      os: ubuntu-latest


                    - name: Windows-latest/MSVC/Debug
                      build_type: Debug
                      generator: Visual Studio 16 2019
                      options: '-DPSTORE_ALWAYS_SPANNING=Yes'
                      os: windows-latest

                    - name: Windows-latest/MSVC/Release
                      build_type: Release
                      generator: Visual Studio 16 2019
                      os: windows-latest

        name: ${{ matrix.name }}
        runs-on: ${{ matrix.os }}

        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 12

            - name: Install Dependencies (Linux)
              if: matrix.os == 'ubuntu-latest' && matrix.apt_name != ''
              run: sudo apt-get install -y ${{ matrix.apt_name }}



            - name: Create Build Environment
              run: cmake -E make_directory ${{ runner.workspace }}/build

            - name: Configure CMake
              shell: bash
              working-directory: ${{ runner.workspace }}/build
              run: |
                  cmake $GITHUB_WORKSPACE                            \
                        -G "${{ matrix.generator }}"                 \
                        -D PSTORE_EXAMPLES=Yes                       \
                        -D CMAKE_BUILD_TYPE=${{ matrix.build_type }} \
                        ${{ matrix.cxx_compiler }}                   \
                        ${{ matrix.options }}

            - name: Build
              working-directory: ${{ runner.workspace }}/build
              shell: bash
              run: cmake --build . --config ${{ matrix.build_type }}

            - name: System Tests
              working-directory: ${{ runner.workspace }}/build
              shell: bash
              run: cmake --build . --config ${{ matrix.build_type }} --target pstore-system-tests
