name: CI Build/Test
# Triggers the workflow on push or pull request events
on: [push, pull_request]
jobs:
    build:
        strategy:
            matrix:
                include:
                    - name: macOS-latest/Xcode/Debug
                      build_type: Debug
                      generator: Xcode
                      options: '-DPSTORE_ALWAYS_SPANNING=Yes'
                      os: macos-latest

                    - name: macOS-latest/Xcode/Release
                      build_type: Release
                      generator: Xcode
                      os: macos-latest


                    - name: Ubuntu-latest/gcc-7.5/Debug
                      apt_install: g++-7
                      build_type: Debug
                      cxx_compiler: -DCMAKE_CXX_COMPILER=g++-7 -DCMAKE_C_COMPILER=gcc-7
                      generator: Unix Makefiles
                      options: '-DPSTORE_ALWAYS_SPANNING=Yes'
                      os: ubuntu-latest

                    - name: Ubuntu-latest/gcc-7.5/Release
                      apt_install: g++-7
                      build_type: Release
                      cxx_compiler: -DCMAKE_CXX_COMPILER=g++-7 -DCMAKE_C_COMPILER=gcc-7
                      generator: Unix Makefiles
                      os: ubuntu-latest


                    - name: Ubuntu-latest/gcc-10/Debug
                      build_type: Debug
                      cxx_compiler: -DCMAKE_CXX_COMPILER=g++-10 -DCMAKE_C_COMPILER=gcc-10
                      generator: Unix Makefiles
                      options: '-DPSTORE_ALWAYS_SPANNING=Yes'
                      os: ubuntu-latest

                    - name: Ubuntu-latest/gcc-10/Release
                      build_type: Release
                      cxx_compiler: -DCMAKE_CXX_COMPILER=g++-10 -DCMAKE_C_COMPILER=gcc-10
                      generator: Unix Makefiles
                      os: ubuntu-latest


                    - name: Ubuntu-latest/clang-8/Debug
                      apt_install: clang-8
                      build_type: Debug
                      cxx_compiler: -DCMAKE_CXX_COMPILER=clang++-8 -DCMAKE_C_COMPILER=clang-8
                      generator: Unix Makefiles
                      options: '-DPSTORE_ALWAYS_SPANNING=Yes'
                      os: ubuntu-latest

                    - name: Ubuntu-latest/clang-8/Release
                      apt_install: clang-8
                      build_type: Release
                      cxx_compiler: -DCMAKE_CXX_COMPILER=clang++-8 -DCMAKE_C_COMPILER=clang-8
                      generator: Unix Makefiles
                      os: ubuntu-latest


                    - name: Ubuntu-latest/clang-12/Debug
                      apt_install: valgrind
                      build_type: Debug
                      cxx_compiler: -DCMAKE_CXX_COMPILER=clang++-12 -DCMAKE_C_COMPILER=clang-12
                      generator: Unix Makefiles
                      options: '-DPSTORE_ALWAYS_SPANNING=Yes -DPSTORE_VALGRIND=Yes -DCMAKE_EXE_LINKER_FLAGS=-fuse-ld=gold'
                      os: ubuntu-latest

                    - name: Ubuntu-latest/clang-12/Release
                      build_type: Release
                      cxx_compiler: -DCMAKE_CXX_COMPILER=clang++-12 -DCMAKE_C_COMPILER=clang-12
                      generator: Unix Makefiles
                      options: '-DCMAKE_EXE_LINKER_FLAGS=-fuse-ld=gold'
                      os: ubuntu-latest


                    - name: Windows-latest/MSVC/Debug
                      build_type: Debug
                      generator: Visual Studio 17 2022
                      options: '-DPSTORE_ALWAYS_SPANNING=Yes'
                      os: windows-latest

                    - name: Windows-latest/MSVC/Release
                      build_type: Release
                      generator: Visual Studio 16 2019
                      os: windows-latest

        name: ${{ matrix.name }}
        runs-on: ${{ matrix.os }}

        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 12

            - name: Install Dependencies (Linux)
              if: matrix.os == 'ubuntu-latest' && matrix.apt_install != ''
              run: sudo apt-get install -y ${{ matrix.apt_install }}



            - name: Create Build Environment
              run: cmake -E make_directory ${{ runner.workspace }}/build

            - name: Configure CMake
              shell: bash
              working-directory: ${{ runner.workspace }}/build
              run: |
                  cmake $GITHUB_WORKSPACE                            \
                        -G "${{ matrix.generator }}"                 \
                        -D PSTORE_EXAMPLES=Yes                       \
                        -D PSTORE_NOISY_UNIT_TESTS=Yes               \
                        -D PSTORE_WERROR=Yes                         \
                        -D CMAKE_BUILD_TYPE=${{ matrix.build_type }} \
                        ${{ matrix.cxx_compiler }}                   \
                        ${{ matrix.options }}

            - name: Build
              working-directory: ${{ runner.workspace }}/build
              shell: bash
              run: cmake --build . --config ${{ matrix.build_type }}

            - name: System Tests
              working-directory: ${{ runner.workspace }}/build
              shell: bash
              run: cmake --build . --config ${{ matrix.build_type }} --target pstore-system-tests

    gcc-5:
        runs-on: ubuntu-latest
        container:
            image: gcc:5.5.0
            options: -u 0
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 12

            - name: Install tools
              run: |
                  apt-get update
                  apt-get install -y ninja-build python3

            - name: Install CMake
              run: |
                  mkdir /download
                  cd /download
                  curl -o cmake.tar.gz \
                       --location \
                       https://github.com/Kitware/CMake/releases/download/v3.20.0/cmake-3.20.0-linux-x86_64.tar.gz
                  tar xzf cmake.tar.gz
                  cp -r cmake-3.20.0-linux-x86_64/* /usr

            - name: Create Build Environment
              run: cmake -E make_directory ${{ runner.workspace }}/build

            - name: Configure CMake
              shell: bash
              run: |
                  cd "${{ runner.workspace }}/build"
                  cmake                           \
                      -G Ninja                    \
                      -D PSTORE_EXAMPLES=Yes      \
                      -D CMAKE_BUILD_TYPE=Release \
                      "$GITHUB_WORKSPACE"

            - name: Build
              shell: bash
              run: |
                  cd "${{ runner.workspace }}/build"
                  cmake --build . --config Release

            - name: System Tests
              shell: bash
              run: |
                  cd "${{ runner.workspace }}/build"
                  cmake                            \
                      --build .                    \
                      --config Release             \
                      --target pstore-system-tests
